/**
 * Builds the report map page into one self-contained HTML string, the way
 * MCP Apps expect it, and writes it as a TypeScript module the Worker can
 * import. The resource URI carries a hash of the page, so a host never shows
 * an old map after a deploy.
 *
 * Usage: bun scripts/buildUi.ts
 */
import { createHash } from "node:crypto";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const source = join(root, "ui", "report-map");
const target = join(root, "src", "ui", "generated");

const built = await Bun.build({
    entrypoints: [join(source, "main.ts")],
    target: "browser",
    format: "esm",
    minify: true,
});
if (!built.success || built.outputs[0] === undefined) {
    for (const log of built.logs) {
        console.error(log);
    }
    process.exit(1);
}

const script = (await built.outputs[0].text()).replaceAll("</script", "<\\/script");
const style = await Bun.file(join(source, "style.css")).text();
const page = (await Bun.file(join(source, "index.html")).text())
    .replace("/* STYLE */", () => style)
    .replace("/* SCRIPT */", () => script);

const hash = createHash("sha256").update(page).digest("hex").slice(0, 12);
const module = [
    "// Generated by scripts/buildUi.ts from ui/report-map. Do not edit.",
    `export const REPORT_MAP_URI = "ui://cityvoice/report-map.${hash}.html";`,
    `export const REPORT_MAP_HTML = ${JSON.stringify(page)};`,
    "",
].join("\n");

await mkdir(target, { recursive: true });
await Bun.write(join(target, "reportMap.ts"), module);
console.log(`report map: ${Math.round(page.length / 1024)} KB, ${hash}`);
